# Generated by Django 5.1.3 on 2025-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayitemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'HolidayitemModel',
                'verbose_name_plural': 'HolidayitemModels',
                'db_table': 'HolidayItem',
            },
        ),
    ]
