# Generated by Django 5.1.3 on 2026-02-05 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_phone_and_more'),
        ('api', '0022_tourmodel_sanatories'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='api.tourmodel', verbose_name='Tur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'UserLikeModel',
                'verbose_name_plural': 'UserLikeModels',
                'db_table': 'UserLike',
                'unique_together': {('user', 'tour')},
            },
        ),
    ]
