networks:
  ustatop_backend:
    driver: bridge

volumes:
  pg_data: null
  pycache: null
  media: null
  static: null

services:
  nginx:
    networks:
      - ustatop_backend
    ports:
      - ${PORT:-8001}:80
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - media:/usr/share/nginx/html/resources/media/:ro
      - static:/usr/share/nginx/html/resources/staticfiles/:ro
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - web
  web:
    networks:
      - ustatop_backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
      - SCRIPT=${SCRIPT:-entrypoint-server.sh}
    volumes:
      - media:/code/resources/media/
      - static:/code/resources/staticfiles/
      - pycache:/var/cache/pycache
    depends_on:
      - db
      - redis
  db:
    networks:
      - ustatop_backend
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '2309'
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    networks:
      - ustatop_backend
    restart: always

    image: redis
