# Generated by Django 5.1.3 on 2025-08-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'BlogModel',
                'verbose_name_plural': 'BlogModels',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='TourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('image', models.ImageField(upload_to='tour/', verbose_name='Image')),
                ('date', models.IntegerField(blank=True, null=True, verbose_name='Kun')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mashhurmi ?')),
                ('is_new', models.BooleanField(default=True, verbose_name='Yangi ?')),
            ],
            options={
                'verbose_name': 'TourModel',
                'verbose_name_plural': 'TourModels',
                'db_table': 'tour',
            },
        ),
    ]
