# Generated by Django 5.1.3 on 2025-09-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tourimagemodel_blogmodel_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourimagemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='tourimagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='tourimagemodel',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.tourmodel'),
        ),
    ]
