# Generated by Django 5.1.3 on 2025-09-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tourimagemodel_name_tourimagemodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='holidays')),
            ],
            options={
                'verbose_name': 'HolidaysModel',
                'verbose_name_plural': 'HolidaysModels',
                'db_table': 'holidays',
            },
        ),
        migrations.CreateModel(
            name='HolidaysimageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images')),
                ('holidays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdays', to='api.holidaysmodel')),
            ],
            options={
                'verbose_name': 'HolidaysimageModel',
                'verbose_name_plural': 'HolidaysimageModels',
                'db_table': 'holidaysImage',
            },
        ),
    ]
