# Generated by Django 5.1.3 on 2025-09-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_holidayitemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='banner/')),
            ],
            options={
                'verbose_name': 'BannerModel',
                'verbose_name_plural': 'BannerModels',
                'db_table': 'baner',
            },
        ),
    ]
