# Generated by Django 5.1.3 on 2025-09-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_categorymodel_tourmodel_slug_tourmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourmodel',
            name='slug',
        ),
    ]
