# Generated by Django 5.1.3 on 2025-09-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_blogmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmodel',
            name='maps',
            field=models.ImageField(blank=True, null=True, upload_to='maps/', verbose_name='Xarita'),
        ),
    ]
