# Generated by Django 5.1.3 on 2025-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tourmodel_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon raqam')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Soni')),
                ('data', models.DateField(blank=True, null=True, verbose_name='kun')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kamment')),
            ],
            options={
                'verbose_name': 'OrderModel',
                'verbose_name_plural': 'OrderModels',
                'db_table': 'order',
            },
        ),
    ]
