# Generated by Django 5.1.3 on 2025-09-13 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='api.tourmodel'),
            preserve_default=False,
        ),
    ]
