# Generated by Django 5.1.3 on 2025-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ordermodel_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel/')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'HotelModel',
                'verbose_name_plural': 'HotelModels',
                'db_table': 'hotel',
            },
        ),
    ]
