# Generated by Django 5.1.3 on 2025-10-06 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_hotelmodel_description_en_hotelmodel_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanatoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('description', models.TextField(verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'SanatoryModel',
                'verbose_name_plural': 'SanatoryModels',
                'db_table': 'sanatory',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='video/', verbose_name='Video')),
                ('sanatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanatorymodel')),
            ],
            options={
                'verbose_name': 'VideoModel',
                'verbose_name_plural': 'VideoModels',
                'db_table': 'video',
            },
        ),
    ]
