# Generated by Django 5.1.3 on 2025-10-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sanatorymodel_videomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanatorymodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='sanatorymodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='sanatorymodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='sanatorymodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sanatorymodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sanatorymodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
