# Generated by Django 5.1.3 on 2025-10-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_sanatorymodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanatorymodel',
            name='image',
            field=models.ImageField(default=1, upload_to='sanatory-images/', verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
