# Generated by Django 5.1.3 on 2025-10-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sanatorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanatorymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='sanatorymodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='sanatorymodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='sanatorymodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='sanatorymodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='sanatory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.sanatorymodel'),
        ),
    ]
