# Generated by Django 5.1.3 on 2025-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_sanatorymodel_slug_alter_sanatorymodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanatorymodel',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
