# Generated by Django 5.1.3 on 2025-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_sanatorymodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanatorymodel',
            name='date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kun'),
        ),
    ]
