# Generated by Django 5.1.3 on 2026-02-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_sanatorymodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmodel',
            name='sanatories',
            field=models.ManyToManyField(blank=True, related_name='tours', to='api.sanatorymodel', verbose_name='Sanatoriyalar'),
        ),
    ]
